GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjYzODczNTI3LCJleHAiOjE2NjM4NzM1NDJ9.FnPgxW25uz2QEUGYlOwh2dZ1v18aa_Vz_QZmFDgELHc

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjYzODczNzUwfQ.xZ4vvmZD0_zDzZWRMgrPWrW4Hgi7trZUJdn1-eCAB1o"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjYzODczNzUwfQ.xZ4vvmZD0_zDzZWRMgrPWrW4Hgi7trZUJdn1-eCAB1o"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}